#!/bin/bash

users=(000581357 000526758 000058418) 
passwords=(ZV0VSDKS 19JSAQ5M S33TK41K)

python webcrawler.py ${users[0]} ${passwords[0]}
python webcrawler.py ${users[1]} ${passwords[1]}
python webcrawler.py ${users[2]} ${passwords[2]}
